namespace MyORM.Test.Models
{
    public class Customer
    {
        public long CustomerId { get; set; }
        
        public string FirstName { get; set; }

        public string LastName { get; set; }

        // Non DB property, generated by combination of FirstName and LastName
        public string CustomerName { get; set; }
    }
}
